# This is a basic workflow to help you get started with Actions

name: TEST

on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  runPHPCSInspection:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install NPM dependencies
        run: npm install
      - name: Install Comoser dependencies
        run: composer install
      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
